### ISSUE TITLE
关于BraTS 2019和BraTS 2020 validation数据集上传官方服务器的问题

### ISSUE THREAD

**Issue by VinyehShaw** [jiangyu945/S2CA-Net#1]
作者大大你好，
文章当中提到的Since the ground-truth of the validation set is not publicly available, the performance is validated via the official server. 我想请问在cbica平台上提交是具体如何进行的，我按照提示上所写的ID.nii.gz格式进行上传，返回的csv结果是GroundTruthSeg/NotFound。文章对比实验里的Dice Score和 Hausdorff Dist是官方服务器自动给出的吗，谢谢！

**Comment by Eight3H** [comment]
> 作者大大你好， 文章当中提到的Since the ground-truth of the validation set is not publicly available, the performance is validated via the official server. 我想请问在cbica平台上提交是具体如何进行的，我按照提示上所写的ID.nii.gz格式进行上传，返回的csv结果是GroundTruthSeg/NotFound。文章对比实验里的Dice Score和 Hausdorff Dist是官方服务器自动给出的吗，谢谢！

可以留个联系方式交流一下吗，我做的也是这个，我也是官网验证的，但我返回是正确的
